Tech 4377 move value class
Invoca/value_class pull request #1
Opened 2020-04-16 21:26 UTC by primiti

This gem started with a clone of active table set.  This is the work to remove active table set from the gem and leave behind just a Value Class gem.

2020-04-16 22:03 UTC, nburwell reviewed
Saw this notification go by, probably not ready for review yet.. just had a few comments though!

2020-04-16 22:03 UTC, nburwell commented on value_class.gemspec
> +  spec.add_dependency 'rails', '~> 4.2'
can you remove rails as a dependency I hope?

2020-04-16 22:03 UTC, nburwell commented on value_class.gemspec
> +  spec.add_development_dependency 'rubocop', '0.74.0'
Our best practice is to specify dev dependencies in the Gemfile versus in the gemspec (https://ringrevenue.atlassian.net/wiki/spaces/DEV/pages/26116204/Versioning+and+Dependencies)

2020-04-17 17:15 UTC, alecjacobs5401 requested changes
So, this is kind of unfortunate.

This gem is public, but `active-table-set` is private. This means that anyone can view the version of `active-table-set` this was based off of because we included `active-table-set` in the git history of this gem.

I'm assuming we don't want to expose a private gem, so we either need to make this private or we need to clean the git history of anything `active-table-set` by rebasing and never including active table set..which may be hard.

That, or, we need to start fresh and delete this repo


Also, it looks like we didn't push a prerelease version for testing, so we'll have to bump the version again based on any feedback that is applied

2020-04-17 17:15 UTC, alecjacobs5401 commented on .gitignore
> +.rubocop-http*
need a newline here

2020-04-17 17:15 UTC, alecjacobs5401 commented on CHANGELOG.md
> +- Cloned from Active Table Set
Maybe we could link to active table set here?

2020-04-17 17:15 UTC, alecjacobs5401 commented on Gemfile
>  gem 'attr_comparable',                  git: 'git@github.com:Invoca/attr_comparable',    ref: '9daa7a7fb935c1ab5bf1402c47aba19756b66e4f'
It looks like `attr_comparable` has had its latest version (`v0.2.0`) pushed to `rubygems`.

Could we pull from there instead of the git sha since that is our best practice now?

Side note, we should probably move it into the `gemspec` declaration if its an actual dependency based on [Best Practices](https://ringrevenue.atlassian.net/wiki/spaces/DEV/pages/26116204/Versioning+and+Dependencies)

2020-04-17 17:15 UTC, alecjacobs5401 commented on CHANGELOG.md
> +## [1.0.0]
Note: You've marked this release as `v.1.0.0` but the [Version File](https://github.com/Invoca/value_class/blob/8c8c20312d2a101af43d0333420df480c5cf30e2/lib/value_class/version.rb#L4) is claiming `0.1.0`

2020-04-17 17:15 UTC, alecjacobs5401 commented on Rakefile
> +task default: [:spec, :rubocop]
need a newline here

2020-04-17 17:15 UTC, alecjacobs5401 commented on value_class.gemspec
> +  spec.add_dependency 'rails', '~> 4.2'
Seconding this

2020-04-17 17:15 UTC, alecjacobs5401 commented on value_class.gemspec
> +  spec.add_dependency 'attr_comparable'
Ah, looks like we have it defined in both. Can we remove the one in the `Gemfile` and prefer this one with the version declared? (or just updated in the lockfile to reflect latest released version)

2020-04-17 17:15 UTC, alecjacobs5401 commented on value_class.gemspec
> +  end
This gem is public, right? Should we be pushing this to rubygems and not gem fury as such?

2020-04-17 17:15 UTC, alecjacobs5401 commented on CHANGELOG.md
> +- Cloned from Active Table Set
Hmm, `active-table-set` is a private gem and this is public though...

2020-04-17 20:59 UTC, primiti commented
Github didn't give me a good place to comment about active table set being in the commit history.  The only reason active table set is private is because we don't want to support it and I am not sure it is general enough for the community.  I am not worried about company confidential information being in the history.   I would rather keep the history intact.

2020-05-01 20:50 UTC, primiti commented on value_class.gemspec
> +  spec.add_dependency 'rails', '~> 4.2'
Done - this did add a little risk - we were using hash_with_indifferent_access as the return value for the configuration.  I am happier removing it, but there were some changes in Active Table Set where it was using strings as keys.

2020-05-01 20:57 UTC, alecjacobs5401 approved these changes
LGTM

2020-05-01 20:57 UTC, alecjacobs5401 commented on value_class.gemspec
> +  spec.add_dependency 'attr_comparable', '~> 0.2'
👏

2020-05-01 23:00 UTC, merged